#pragma config(Sensor, dgtl1,  rdist,          sensorDigitalIn)
#pragma config(Sensor, dgtl2,  rdist,          sensorDigitalOut)
#pragma config(Sensor, dgtl3,  ldist,          sensorDigitalIn)
#pragma config(Sensor, dgtl4,  ldist,          sensorDigitalOut)
#pragma config(Motor,  port1,           imakespin,     tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port5,           theymakespin,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          spinimake,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task Spintheymake(){

}

task main()
{
	while(true){

	motor[imakespin] = vexRT[Ch3];
	motor[spinimake] = vexRT[Ch3];

		if(vexRT[Btn8L] == 1){
			startTask(Spintheymake);
		}

		else if(vexRT[Btn8D] == 1){
			stopTask(Spintheymake);
		}
	}
}
